# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

RUST_MIN_VER="1.89"

inherit cargo desktop optfeature xdg

DESCRIPTION="Wayland screen streamer: tile-diffed WebP over WebRTC to any browser"
HOMEPAGE="https://github.com/tarilka0gg/Ring-2Zero"
SRC_URI="
	https://github.com/tarilka0gg/Ring-2Zero/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"
if [[ ${PKGBUMPING} != ${PVR} ]]; then
	SRC_URI+="
		https://github.com/tarilka0gg/Ring-2Zero/releases/download/v${PV}/${P}-crates.tar.xz
	"
fi
S="${WORKDIR}/Ring-2Zero-${PV}"
# vendored crates from the release asset, unpacked next to the sources
ECARGO_VENDOR="${WORKDIR}/${P}-crates"

LICENSE="MIT"
# Dependent crate licenses (generated by packaging/gentoo/gen-ebuild-data.py)
LICENSE+=" Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD BSD-1 BSD-2 Boost-1.0 ISC LGPL-2.1+ MIT Unicode-3.0 Unlicense ZLIB openssl"
SLOT="0"
KEYWORDS="~amd64"
IUSE="pipewire"

RDEPEND="
	dev-libs/wayland
	media-libs/mesa
	x11-libs/libdrm
	pipewire? (
		media-video/pipewire:=
		sys-apps/dbus
	)
"
DEPEND="${RDEPEND}"
# .cargo/config.toml links with clang
BDEPEND="
	llvm-core/clang
	virtual/pkgconfig
"

QA_FLAGS_IGNORED="usr/bin/ring-2zero"

pkg_setup() {
	rust_pkg_setup
}

src_configure() {
	local myfeatures=( $(usev pipewire pipewire_capture) )
	cargo_src_configure
}

src_compile() {
	cargo_src_compile --bin ring-2zero
}

src_test() {
	cargo_src_test --lib --bins --
}

src_install() {
	cargo_src_install --bin ring-2zero
	dosym ring-2zero /usr/bin/r2zr

	doman man/ring-2zero.1
	domenu packaging/io.github.tarilka0gg.Ring2Zero.desktop
	insinto /usr/share/metainfo
	doins packaging/io.github.tarilka0gg.Ring2Zero.metainfo.xml
	insinto /usr/share/icons/hicolor/scalable/apps
	doins packaging/icons/ring-2zero.svg
	dodoc CHANGELOG.md README.md
}

pkg_postinst() {
	xdg_pkg_postinst
	optfeature "TURN/STUN servers for streaming across NAT" net-im/coturn
}

pkg_postrm() {
	xdg_pkg_postrm
}
